FROM ricmm/parity:ARM64V8-UPSTREAM-UNSTABLE

RUN apt-get update; apt-get install -y curl jq; apt-get clean; rm -rf /var/lib/apt/lists

ADD ./health /

ADD ./tobalaba-peers /

EXPOSE 30303 8545 8546 5001 8083 8082 8008

HEALTHCHECK --start-period=10s --timeout=10s --interval=30s --retries=10 \
	CMD /health

CMD ["--jsonrpc-apis","all","--reserved-peers","/tobalaba-peers"]
