FROM ricmm/energyweb-client:ARM64V8-UPSTREAM-UNSTABLE

RUN apt-get update; apt-get install -y curl jq; apt-get clean; rm -rf /var/lib/apt/lists

ADD ./tobalaba-peers /

EXPOSE 30303 8545 8546 5001 8083 8082 8008

CMD ["--jsonrpc-apis","all","--reserved-peers","/tobalaba-peers"]