# This is an example. Please use it as such. For more info read swagger documentation and wikipedia article on REST protocol https://en.wikipedia.org/wiki/Representational_state_transfer
# Please mind that the generators for servers and clients can be outdated and are open source contribuitons.

# Don't change swagger: "2.0".
swagger: '2.0'
info:
  title: Energy Measurement API
  description: Company name, project name, purpose of the api creation, date of last update, sometimes code author name.
  # Always change the version of the API endpoints and contracts, keeping compatibility in the major version. Also keep the previous versions available for retro compatibility.
  # I.E. Client versions 1.*.* are able to access the /v1/* endpoints without changing any code. Minor versions only fix typos and unpredicted behavior, adding endpoints is possible but not removing previous ones.
  # When version 2.0.0 is release under /v2/* endpoint, /v1 is kept for keeping version 1.*.* working.
  version: "1.0.0"
# the domain of the service, site can be added like api.site_name.your_company.com, keeping site_name.your_company.com for dashboards or any other webapp based on api.site_name.your_company.com.
host: api.yourcompany.com
# array of all schemes that your API supports
# note: DO NOT use http with authentication enabled.
# Either use http only with no authentication OR https + auth.
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
securityDefinitions:
  basicAuth:
    type: basic
# To apply Basic auth to the whole API:
security:
  - basicAuth: []
paths:
  /consumed:
    get:
      summary: Consumed energy
      description: Energy consumed measured in Mega Watts during a certain period.
      tags:
        - Energy Consumer
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 10)
          required: false
          default: 5
          type: integer
          format: int32
        - name: start
          in: query
          description: Date in RFC 3339 format. ie. 2018-03-14T17:11:19+00:00
          required: false
          default: last_hour
          type: string
        - name: end
          in: query
          description: Date in RFC 3339 format. ie. 2018-03-14T17:12:20+00:00
          required: false
          default: now
          type: string
      responses:
        # 200 when the measuredEnergy array has at least one entry.
        # 400 if the array is empty or request is malformed.
        # 401 for bad credentials or lacking auth header.
        # 501 if the location produces energy only, return 501 - Not Implemented.
        200:
          description: An array of measured energy
          schema:
            type: object
            items:
              $ref: '#/definitions/MeasuredEnergyOnDevice'
        401:
          $ref: "#/responses/Unauthorized"
        400:
          $ref: "#/responses/BadRequest"
        501:
          $ref: "#/responses/NotImplemented"
    post:
      tags:
        - Not Implemented
      responses:
        405:
          $ref: '#/responses/MethodNotAllowed'
        501:
          $ref: "#/responses/NotImplemented"
    put:
      tags:
        - Not Implemented
      responses:
        405:
          $ref: '#/responses/MethodNotAllowed'
        501:
          $ref: "#/responses/NotImplemented"
    delete:
      tags:
        - Not Implemented
      responses:
        405:
          $ref: '#/responses/MethodNotAllowed'
        501:
          $ref: "#/responses/NotImplemented"
  /produced:
    get:
      summary: Produced energy
      description: Energy produced measured in Mega Watts during a certain period.
      tags:
        - Energy Producer
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 10)
          required: false
          default: 5
          type: integer
          format: int32
        - name: start
          in: query
          description: Date in RFC 3339 format. ie. 2018-03-14T17:11:19+00:00
          required: false
          default: last_hour
          type: string
        - name: end
          in: query
          description: Date in RFC 3339 format. ie. 2018-03-14T17:12:20+00:00
          required: false
          default: now
          type: string
      responses:
        # 200 when the measuredEnergy array has at least one entry.
        # 400 if the array is empty or request is malformed.
        # 401 for bad credentials or lacking auth header.
        # 501 if the location produces energy only, return 501 - Not Implemented.
        200:
          description: An array of measured energy
          schema:
            type: array
            items:
              $ref: '#/definitions/MeasuredEnergyOnDevice'
        401:
          $ref: "#/responses/Unauthorized"
        400:
          $ref: "#/responses/BadRequest"
        501:
          $ref: "#/responses/NotImplemented"
    post:
      tags:
        - Not Implemented
      responses:
        405:
          $ref: '#/responses/MethodNotAllowed'
        501:
          $ref: "#/responses/NotImplemented"
    put:
      tags:
        - Not Implemented
      responses:
        405:
          $ref: '#/responses/MethodNotAllowed'
        501:
          $ref: "#/responses/NotImplemented"
    delete:
      tags:
        - Not Implemented
      responses:
        405:
          $ref: '#/responses/MethodNotAllowed'
        501:
          $ref: "#/responses/NotImplemented"

responses:
  Unauthorized:
    description: Authentication information is missing or invalid
    headers:
      WWW_Authenticate:
        type: string
  MethodNotAllowed:
    description: Method not allowed. Check headers for allowed methods.
    headers:
      Access-Control-Allow-Methods:
        type: string
  NotImplemented:
    description: Endpoint not implemented
  BadRequest:
    description: Limit must be non-zero positive integer | Dates must be in RFC 3339 format | Start date must be higher than end date

definitions:
  Device:
    description: Energy measuring device
    type: object
    properties:
      manufacturer:
        type: string
        description: Device Manufacturer
      model:
        type: string
        description: Device Model
      serial_number:
        type: string
        description: Device Serial Number
      latitude:
        type: string
        description: Geolocation point latitude
      longitude:
        type: string
        description: Geolocation point latitude
  MeasuredEnergy:
    description: Energy measured at a certain time.
    type: object
    properties:
      accumulated_power:
        type: number
        description: Registered in Mega Watts
      measurement_time:
        type: integer
        description: Time of measurement in the device, in RFC 3339 format. ie. 2018-03-14T17:12:20+00:00
  MeasuredEnergyOnDevice:
    type: object
    properties:
      count:
        type: integer
        description: Page count
      previous:
        type: string
        description: Link to previous page
      next:
        type: string
        description: Link to next page
      device:
        $ref: '#/definitions/Device'
      measuredEnergy:
        type: array
        items:
          $ref: '#/definitions/MeasuredEnergy'
